nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['X-Requested-With', 'X-Auth-Token', 'Content-Type', 'Origin', 'Cache-Control', 'Pragma', 'Authorization', 'Accept', 'Accept-Encoding', 'X-Login-Origin', 'responseType']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
