security:
    encoders:
        App\Entity\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            json_login:
                check_path: login
                username_path: email
                password_path: password
    hide_user_not_found: false
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email
